keys:
  - &juun 3BE0D40337391EAFBBE324B142A74ED0B66BCE27
  - &juun-server age1dzn365xsvkqgczmk8dfdhzqvql9ft4luc642naswxf7mcftuzv7swlw34t

creation_rules:
  - path_regex: nix/(?:[^/]+/)*[^/]+\.(yaml|json|env|ini|norg)$
    key_groups:
    - pgp:
        - *juun
      age:
        - *juun-server
